const BOT_TOKEN = process.env.BOT_TOKEN;
const GUILD_ID = process.env.GUILD_ID;
const API_KEY = process.env.API_KEY;
const GROUP_ID = process.env.GROUP_ID;
const PUBLIC_BASE_URL = process.env.PUBLIC_BASE_URL
  || (process.env.RAILWAY_PUBLIC_DOMAIN ? `https://${process.env.RAILWAY_PUBLIC_DOMAIN}` : "");
const DISCORD_OAUTH_CLIENT_ID = process.env.DISCORD_OAUTH_CLIENT_ID || process.env.DISCORD_CLIENT_ID || "";
const DISCORD_OAUTH_CLIENT_SECRET = process.env.DISCORD_OAUTH_CLIENT_SECRET || process.env.DISCORD_CLIENT_SECRET || "";
const DISCORD_OAUTH_REDIRECT_URI = process.env.DISCORD_OAUTH_REDIRECT_URI || (
  PUBLIC_BASE_URL ? `${PUBLIC_BASE_URL.replace(/\/$/, "")}/oauth/discord/callback` : ""
);
const DISCORD_OAUTH_SCOPES = process.env.DISCORD_OAUTH_SCOPES || "identify";
const ROBLOX_OAUTH_CLIENT_ID = process.env.ROBLOX_OAUTH_CLIENT_ID || "";
const ROBLOX_OAUTH_CLIENT_SECRET = process.env.ROBLOX_OAUTH_CLIENT_SECRET || "";
const ROBLOX_OAUTH_REDIRECT_URI = process.env.ROBLOX_OAUTH_REDIRECT_URI || (
  PUBLIC_BASE_URL ? `${PUBLIC_BASE_URL.replace(/\/$/, "")}/oauth/roblox/callback` : ""
);
const ROBLOX_OAUTH_SCOPES = process.env.ROBLOX_OAUTH_SCOPES || "openid profile";

const VERIFIED_ROLE_ID = "1477834795512893520";
const MOD_ROLE_ID = "1477872215801331763";

const WALD_ROLE_ID = "1415902349192331381";
const UNWAVED_ROLE_ID = process.env.UNWAVED_ROLE_ID || WALD_ROLE_ID;
const ENVISIONED_ROLE_ID = "1415902349192331383";
const WIPE_CHANNEL_ID = "1492143731921387520";
const DEATH_CHANNEL_ID = "1415902351985872908";
const EXAM_SERVICE_CHANNEL_ID = "1415902351985872909";
const BOT_TRANSCRIPTS_CHANNEL_ID = "1493921133605683322";
const EVENT_LOGS_CHANNEL_ID = "1493925383706513419";
const EVENT_STATUS_CHANNEL_ID = "1493917062953701407";
const TALENTS_CHANNEL_ID = "1493382684217577472";
const ANTICHEAT_CHANNEL_ID = process.env.ANTICHEAT_CHANNEL_ID || "1415902351985872911";
const COMMAND_LOG_CHANNEL_ID = process.env.COMMAND_LOG_CHANNEL_ID || "1415902351985872912";
const VERIFICATION_CHANNEL_ID = process.env.VERIFICATION_CHANNEL_ID || "";

const EDITABLE_POST_MODAL_PREFIX = "editablePost";
const EDITABLE_POST_TITLE_FIELD_ID = "title";
const EDITABLE_POST_BODY_FIELD_ID = "body";

const roleMap = {
  "Crimson Blades": "1477828058949091481",
  Vanguard: "1477828166025220178",
  Fame: "1477827943278317660",
  Chasers: "1477828132269457559",
};

const ADMIN_ACTION_WAIT_TIMEOUT_MS = 15000;
const ADMIN_ACTION_CLAIM_TIMEOUT_MS = 60000;
const ADMIN_ACTION_RETENTION_MS = 30 * 60 * 1000;
const TALENT_LOOKUP_WAIT_TIMEOUT_MS = 15000;
const TALENT_LOOKUP_CLAIM_TIMEOUT_MS = 60000;
const TALENT_LOOKUP_RETENTION_MS = 30 * 60 * 1000;
const INTERACTION_FOLLOW_UP_WINDOW_MS = 15 * 60 * 1000;
const EVENT_SESSION_RETENTION_LIMIT = 250;
const INACTIVITY_DAYS = Math.max(1, Number.parseInt(process.env.INACTIVITY_DAYS || "14", 10) || 14);
const INACTIVITY_NEAR_DAYS = Math.max(1, Number.parseInt(process.env.INACTIVITY_NEAR_DAYS || "7", 10) || 7);
const INACTIVITY_CONFIRM_LIMIT = Math.max(1, Number.parseInt(process.env.INACTIVITY_CONFIRM_LIMIT || "25", 10) || 25);
const INACTIVITY_MAX_LIMIT = Math.max(INACTIVITY_CONFIRM_LIMIT, Number.parseInt(process.env.INACTIVITY_MAX_LIMIT || "100", 10) || 100);
const INACTIVITY_EXEMPT_ROLE_IDS = new Set(
  String(process.env.INACTIVITY_EXEMPT_ROLE_IDS || MOD_ROLE_ID || "")
    .split(",")
    .map((roleId) => roleId.trim())
    .filter(Boolean)
);

module.exports = {
  ADMIN_ACTION_CLAIM_TIMEOUT_MS,
  ADMIN_ACTION_RETENTION_MS,
  ADMIN_ACTION_WAIT_TIMEOUT_MS,
  ANTICHEAT_CHANNEL_ID,
  API_KEY,
  BOT_TOKEN,
  BOT_TRANSCRIPTS_CHANNEL_ID,
  COMMAND_LOG_CHANNEL_ID,
  DEATH_CHANNEL_ID,
  DISCORD_OAUTH_CLIENT_ID,
  DISCORD_OAUTH_CLIENT_SECRET,
  DISCORD_OAUTH_REDIRECT_URI,
  DISCORD_OAUTH_SCOPES,
  EDITABLE_POST_BODY_FIELD_ID,
  EDITABLE_POST_MODAL_PREFIX,
  EDITABLE_POST_TITLE_FIELD_ID,
  ENVISIONED_ROLE_ID,
  EVENT_LOGS_CHANNEL_ID,
  EVENT_SESSION_RETENTION_LIMIT,
  EVENT_STATUS_CHANNEL_ID,
  EXAM_SERVICE_CHANNEL_ID,
  GROUP_ID,
  GUILD_ID,
  INACTIVITY_CONFIRM_LIMIT,
  INACTIVITY_DAYS,
  INACTIVITY_EXEMPT_ROLE_IDS,
  INACTIVITY_MAX_LIMIT,
  INACTIVITY_NEAR_DAYS,
  INTERACTION_FOLLOW_UP_WINDOW_MS,
  MOD_ROLE_ID,
  PUBLIC_BASE_URL,
  ROBLOX_OAUTH_CLIENT_ID,
  ROBLOX_OAUTH_CLIENT_SECRET,
  ROBLOX_OAUTH_REDIRECT_URI,
  ROBLOX_OAUTH_SCOPES,
  TALENTS_CHANNEL_ID,
  TALENT_LOOKUP_CLAIM_TIMEOUT_MS,
  TALENT_LOOKUP_RETENTION_MS,
  TALENT_LOOKUP_WAIT_TIMEOUT_MS,
  UNWAVED_ROLE_ID,
  VERIFIED_ROLE_ID,
  VERIFICATION_CHANNEL_ID,
  WALD_ROLE_ID,
  WIPE_CHANNEL_ID,
  roleMap,
};
